image: 
  file: Dockerfile

vscode:
  extensions:
    - vsls-contrib.codetour
    - auchenberg.vscode-browser-preview
    - synedra.auto-run-command

checkoutLocation: "."

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
ports:
  - port: 8888
    onOpen: open-preview
    visibility: public
  - port: 3000
    onOpen: ignore 
    visibility: public
  - port: 8443
    onOpen: ignore
    visibility: public
